
import React, { useState } from 'react';
import { GoogleGenAI } from '@google/genai';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [imageUrl, setImageUrl] = useState<string | null>(null);

  const handleGenerateImage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim() || isLoading) return;

    setIsLoading(true);
    setError(null);
    setImageUrl(null);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
        },
      });

      if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes = response.generatedImages[0].image.imageBytes;
        const url = `data:image/png;base64,${base64ImageBytes}`;
        setImageUrl(url);
      } else {
        throw new Error('No image was generated. The response may have been blocked.');
      }

    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An unknown error occurred.';
      console.error(err);
      setError(`Failed to generate image. ${errorMessage}`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full max-w-4xl mx-auto">
      <div className="w-full p-4 bg-gray-800/50 rounded-lg shadow-lg mb-6">
        <form onSubmit={handleGenerateImage} className="flex flex-col sm:flex-row items-center gap-3">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Describe the image you want to create..."
            rows={2}
            disabled={isLoading}
            className="flex-1 w-full p-3 bg-gray-700 rounded-lg border border-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50 resize-none"
          />
          <button
            type="submit"
            disabled={isLoading || !prompt.trim()}
            className="bg-indigo-600 text-white p-3 rounded-lg font-semibold hover:bg-indigo-700 disabled:bg-indigo-800 disabled:cursor-not-allowed transition-colors flex items-center justify-center w-full sm:w-40 h-[58px]"
          >
            {isLoading ? (
              <div className="w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
            ) : (
                <div className="flex items-center gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-5 h-5"><path fillRule="evenodd" d="M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm.75-13a.75.75 0 0 0-1.5 0v5.5a.75.75 0 0 0 1.5 0v-5.5ZM10 12.25a.75.75 0 0 1 .75.75v.01a.75.75 0 0 1-1.5 0v-.01a.75.75 0 0 1 .75-.75Z" clipRule="evenodd" /></svg>
                    <span>Generate</span>
                </div>
            )}
          </button>
        </form>
      </div>

       {error && (
            <div className="p-4 mb-6 bg-red-500/20 text-red-300 text-sm rounded-lg text-center">
                <strong>Error:</strong> {error}
            </div>
        )}

      <div className="flex-grow w-full bg-gray-800/50 rounded-lg shadow-lg flex items-center justify-center p-4 min-h-[300px] sm:min-h-[400px]">
        {isLoading ? (
          <div className="text-center text-gray-400">
             <div className="w-12 h-12 border-4 border-indigo-400 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-lg">Generating your image...</p>
             <p className="text-sm">This can take a moment.</p>
          </div>
        ) : imageUrl ? (
          <img src={imageUrl} alt="Generated by AI" className="max-w-full max-h-full object-contain rounded-md" />
        ) : (
            <div className="text-center text-gray-500">
                <div className="w-16 h-16 mx-auto mb-4 p-3 rounded-2xl bg-gray-700/50 text-gray-400">
                     <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path fillRule="evenodd" d="M1.5 6a2.25 2.25 0 0 1 2.25-2.25h16.5A2.25 2.25 0 0 1 22.5 6v12a2.25 2.25 0 0 1-2.25 2.25H3.75A2.25 2.25 0 0 1 1.5 18V6ZM3 16.06l2.755-2.755a.75.75 0 0 1 1.06 0l3.72 3.72a.75.75 0 0 0 1.06 0l3.53-3.53a.75.75 0 0 1 1.06 0l2.122 2.122v-6.31L15.28 9.22a.75.75 0 0 0-1.06 0l-3.53 3.53a.75.75 0 0 1-1.06 0L6.22 9.28a.75.75 0 0 0-1.06 0L3 11.44v4.62Z" clipRule="evenodd" /></svg>
                </div>
                <h2 className="text-xl font-semibold">Your generated image will appear here.</h2>
                <p>Describe what you want to see in the box above.</p>
            </div>
        )}
      </div>
    </div>
  );
};

export default ImageGenerator;
